FROM nvcr.io/nvidia/tensorflow:19.09-py3

COPY ./keys/id_rsa.pub /tmp/tmp.pub

RUN mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat /tmp/tmp.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && rm -f /tmp/tmp.pub

RUN apt-get update && apt-get --yes install  openssh-server

RUN git config --global user.email "paloukari@hotmail.com"
RUN git config --global user.name "paloukari"

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENTRYPOINT service ssh restart && bash
