FROM nvcr.io/nvidia/tensorflow:19.09-py3

COPY ./keys/id_rsa.pub /tmp/tmp.pub

RUN mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat /tmp/tmp.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && rm -f /tmp/tmp.pub

RUN apt update && apt install Y openssh-server

WORKDIR /src

ENTRYPOINT service ssh restart && bash
